[package]
name = "sculpt-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.66"
quote = "1.0.36"
proc-macro2 = "1.0.84"

[build-dependencies]
sculpt = { git = "https://github.com/VictorVanWeyenberg/sculpt.git", branch = "development" }
